version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "qa/api-team"
    assignees:
      - "bughunterX"
    commit-message:
      prefix: "deps:"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    
    groups:
      playwright:
        patterns:
          - "@playwright/*"
          - "playwright"
      testing:
        patterns:
          - "*test*"
          - "*jest*"
          - "*mocha*"
          - "faker"
      dev-dependencies:
        dependency-type: "development"
    
    ignore:
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    commit-message:
      prefix: "ci:"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"